"""
Python-native type wrappers for the AML LLM SDK.

These types mirror the C structs and enums defined in ``llmsdk.h``,
providing idiomatic Python interfaces (dataclasses and IntEnums).
"""

from dataclasses import dataclass
from enum import IntEnum


class RunStatus(IntEnum):
    """Represents the possible states during an LLM generation process."""

    NORMAL = 0  #: The LLM is currently processing as expected.
    FINISH = 1  #: The LLM has completed the task successfully.
    ERROR = 2   #: The LLM encountered an error during execution.


class RetStatus(IntEnum):
    """Indicates the return status of an LLM SDK API call."""

    SUCCESS = 0  #: The API call completed successfully.
    FAILED = 1   #: The API call failed (generic error).


class SamplingMode(IntEnum):
    """Defines available sampling strategies for output generation."""

    ARG_MAX = 0        #: Argmax sampling – always selects the highest-probability token (deterministic).
    TOP_P = 1          #: Top-P (nucleus) sampling.
    TOP_K = 2          #: Top-K sampling.
    CHAIN_SAMPLER = 3  #: Chain sampler – configurable via sampler_params_json.


class RunMode(IntEnum):
    """Describes the available modes for performing LLM inference."""

    GENERATE = 0  #: Generates text output based on the input prompt.


class MessageType(IntEnum):
    """Type of a generated message fragment (mirrors AML_LLMMessageType)."""

    TEXT = 0        #: Normal answer text.
    REASONING = 1   #: Thinking / reasoning chain content.
    TOOL = 2        #: Tool-call markup content.


@dataclass
class Result:
    """Represents the results generated by the LLM during inference.

    Delivered incrementally via the callback for each token generated.

    Attributes:
        text: Raw bytes — may contain incomplete UTF-8 sequences since
            token-level decoding can split multi-byte characters.
            Accumulate and decode with ``.decode('utf-8', errors='replace')``
            when ready to display.
        token_id: The token ID generated by the current inference step.
        content_type: The :class:`MessageType` of this fragment (text,
            reasoning, or tool). Reasoning fragments should be routed to a
            separate channel (e.g. ``reasoning_content``) rather than the
            answer text.
    """

    text: bytes = b""
    token_id: int = 0
    content_type: int = MessageType.TEXT
